### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by charlescgs** [lapce/floem#671]
Hey, I encountered an issue, when having scroll view, I am unable to scroll with mouse and handle. Only scroll wheel works.

It doesn't work as well in the 'toto-complex' example.

I am using Windows 11 with newest floem master on vello.

**Comment by jrmoulton** [comment]
I think I know what the issue is. There is some padding on the scroll in that example and the scroll is probably missing the events for the scroll bar. The scroll is painting the bar in the right place but the event isn't registering unless the mouse is further right. I should be able to fix it pretty quickly if that is what is going on

**Comment by charlescgs** [comment]
Just checked.. You're right. After remove this line:
```rust
.style(|s| s.padding(10).padding_right(10))
```
..the scroll handle works as expected.. But now is overlapping the view :D
